<?php
add_action("acf/include_fields", function () {
    if (!function_exists("acf_add_local_field_group")) {
        return;
    }

    acf_add_local_field_group([
        "key" => "group_667b13f56d9f7",
        "title" => "Engrave",
        "fields" => [
            [
                "key" => "field_6685a5779ecfa",
                "label" => "Engrave Enable or Disable",
                "name" => "engrave_enable_disable",
                "aria-label" => "",
                "type" => "checkbox",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "choices" => [
                    1 => "Enable Engrave",
                ],
                "default_value" => [
                    0 => "0",
                ],
                "return_format" => "value",
                "layout" => "vertical",
                "allow_custom" => 0,
                "save_custom" => 0,
                "toggle" => 0,
                "custom_choice_button_text" => "Add new choice",
            ],
            [
                'key' => 'field_66aa4cfd879a2',
                'label' => 'Live Preview Engrave Image Width',
                'name' => 'live_preview_engrave_image_width',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_6685a5779ecfa',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 400,
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a131b0431b2',
                'label' => 'Engrave Front Fields',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_6685a5779ecfa',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                "key" => "field_667b14040d358",
                "label" =>
                    "Engrave Front (how many fields would you like to add, and how many characters should each field contain?)",
                "name" => "engrave",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => [
                    [
                        [
                            "field" => "field_6685a5779ecfa",
                            "operator" => "==",
                            "value" => "1",
                        ],
                    ],
                ],
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "pagination" => 0,
                "min" => 1,
                "max" => 5,
                "collapsed" => "",
                "button_label" => "Add Row",
                "rows_per_page" => 20,
                "sub_fields" => [
                    [
                        "key" => "field_667b14170d359",
                        "label" => "Engrave",
                        "name" => "subengrave",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => false,
                        "conditional_logic" => false,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_667b14040d358",
                    ],
                ],
            ],
            [
                "key" => "field_668eee17c9bf8",
                "label" => "Live Preview ( front )",
                "name" => "live_preview_front",
                "aria-label" => "",
                "type" => "image",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "return_format" => "url",
                "library" => "all",
                "min_width" => "",
                "min_height" => "",
                "min_size" => "",
                "max_width" => "",
                "max_height" => "",
                "max_size" => "",
                "mime_types" => "",
                "preview_size" => "medium",
            ],
            [
                'key' => 'field_66a131e6431b3',
                'label' => 'Engrave Back Fields',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_6685a5779ecfa',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                "key" => "field_668da870e45e8",
                "label" =>
                    "Engrave Back (how many fields would you like to add, and how many characters should each field contain?) (copy)",
                "name" => "engrave_back",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => [
                    [
                        [
                            "field" => "field_6685a5779ecfa",
                            "operator" => "==",
                            "value" => "1",
                        ],
                    ],
                ],
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "layout" => "block",
                "pagination" => 0,
                "min" => 1,
                "max" => 5,
                "collapsed" => "",
                "button_label" => "Add Row",
                "rows_per_page" => 20,
                "sub_fields" => [
                    [
                        "key" => "field_668da870e45e9",
                        "label" => "Engrave Back",
                        "name" => "subengrave_back",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => 0,
                        "conditional_logic" => 0,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_668da870e45e8",
                    ],
                ],
            ],
            [
                "key" => "field_668eeed2c9bf9",
                "label" => "Live Preview ( back )",
                "name" => "live_preview_back",
                "aria-label" => "",
                "type" => "image",
                "instructions" => "",
                "required" => 0,
                "conditional_logic" => 0,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "return_format" => "url",
                "library" => "all",
                "min_width" => "",
                "min_height" => "",
                "min_size" => "",
                "max_width" => "",
                "max_height" => "",
                "max_size" => "",
                "mime_types" => "",
                "preview_size" => "medium",
            ],
            [
                'key' => 'field_66a144c2b8043',
                'label' => 'Front Live Engraving Preview Options',
                'name' => '',
                'aria-label' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_6685a5779ecfa',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'placement' => 'top',
                'endpoint' => 0,
            ],
            [
                'key' => 'field_66a148dbb8044',
                'label' => 'Preview Text Padding Top',
                'name' => 'preview_text_padding_top',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14cfeb8045',
                'label' => 'Preview Text Padding Bottom',
                'name' => 'preview_text_padding_bottom',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14d18b8046',
                'label' => 'Preview Text Padding Left',
                'name' => 'preview_text_padding_left',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14d29b8047',
                'label' => 'Preview Text Padding Right',
                'name' => 'preview_text_padding_right',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 1,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14d88b8048',
                'label' => 'Preview Text Font Size',
                'name' => 'preview_text_font_size',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 10,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14da7b8049',
                'label' => 'Preview Text Font Style',
                'name' => 'preview_text_font_style',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 'Arial',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a14de2b804a',
                'label' => 'Preview Text Line Spacing',
                'name' => 'preview_text_line_spacing',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 15,
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ],
            [
                'key' => 'field_66a152cb7f099',
                'label' => 'Preview Text Color',
                'name' => 'preview_text_color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'default_value' => 'black',
                'enable_opacity' => 0,
                'return_format' => 'string',
            ],
            [
                'key' => 'field_66a14e1bb804b',
                'label' => 'Preview Text Orientation',
                'name' => 'preview_text_orientation',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => [
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ],
                'choices' => [
                    'horizontal' => 'Horizontal',
                    'vertical' => 'Vertical',
                ],
                'default_value' => 'horizontal',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
        ],
        [
            'key' => 'field_66a26671e150c',
            'label' => 'Back Live Engraving Preview Options',
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => [
                    [
                        [
                            'field' => 'field_6685a5779ecfa',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'placement' => 'top',
            'endpoint' => 0,
        ],
        [
            'key' => 'field_66a2668de150d',
            'label' => 'Back Preview Text Padding Top',
            'name' => 'back_preview_text_padding_top',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 1,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a2669ae150e',
            'label' => 'Back Preview Text Padding Bottom',
            'name' => 'back_preview_text_padding_bottom',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 1,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266a6e150f',
            'label' => 'Back Preview Text Padding Left',
            'name' => 'back_preview_text_padding_left',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 1,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266b4e1510',
            'label' => 'Back Preview Text Padding Right',
            'name' => 'back_preview_text_padding_right',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 1,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266bfe1511',
            'label' => 'Back Preview Text Font Size',
            'name' => 'back_preview_text_font_size',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 10,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266c7e1512',
            'label' => 'Back Preview Text Font Style',
            'name' => 'back_preview_text_font_style',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 'Arial',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266d2e1513',
            'label' => 'Back Preview Text Line Spacing',
            'name' => 'back_preview_text_line_spacing',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 15,
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ],
        [
            'key' => 'field_66a266dee1514',
            'label' => 'Back Preview Text Color',
            'name' => 'back_preview_text_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'default_value' => 'black',
            'enable_opacity' => 0,
            'return_format' => 'string',
        ],
        [
            'key' => 'field_66a266e9e1515',
            'label' => 'Back Preview Text Orientation',
            'name' => 'back_preview_text_orientation',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => [
                'width' => '',
                'class' => '',
                'id' => '',
            ],
            'choices' => [
                'horizontal' => 'Horizontal',
                'vertical' => 'Vertical',
            ],
            'default_value' => 'horizontal',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'vertical',
            'save_other_choice' => 0,
        ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "product",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => "",
        "active" => true,
        "description" => "",
        "show_in_rest" => 0,
    ]);

    acf_add_local_field_group([
        "key" => "group_667db55d4a511",
        "title" => "engrave order",
        "fields" => [
            [
                "key" => "field_667db574948df",
                "label" => "engrave",
                "name" => "engrave_data",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "shop_order",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => [],
        "active" => true,
        "description" => "",
        "show_in_rest" => false,
    ]);

    acf_add_local_field_group([
        "key" => "group_667c70c8e8e15",
        "title" => "QR Code",
        "fields" => [
            [
                "key" => "field_667c70dc5c626",
                "label" => "Personal Medical Emergency",
                "name" => "personal_medical_emergency",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_667c716c5c627",
                "label" => "QR Code on Front (Engraving Back)",
                "name" => "qr_code_on_front_engraving_back",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_667c72155c628",
                "label" => "Great For Heading",
                "name" => "great_for_heading",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_667c748e5c629",
                "label" => "Great For Bullets",
                "name" => "great_for_bullets",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "min" => 1,
                "max" => 10,
                "layout" => "block",
                "rows_per_page" => 20,
                "button_label" => "Add Row",
                "collapsed" => "",
                "sub_fields" => [
                    [
                        "key" => "field_667c74c55c62a",
                        "label" => "Bullets",
                        "name" => "bullets",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => false,
                        "conditional_logic" => false,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_667c748e5c629",
                    ],
                ],
            ],
            [
                "key" => "field_667c74e85c62b",
                "label" => "Also Includes Heading",
                "name" => "also_includes_heading",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_667c74ff5c62c",
                "label" => "Also Includes Text",
                "name" => "also_includes_text",
                "aria-label" => "",
                "type" => "text",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "default_value" => "",
                "maxlength" => "",
                "placeholder" => "",
                "prepend" => "",
                "append" => "",
            ],
            [
                "key" => "field_667c75085c62d",
                "label" => "Also Includes Bullets",
                "name" => "also_includes_bullets",
                "aria-label" => "",
                "type" => "repeater",
                "instructions" => "",
                "required" => false,
                "conditional_logic" => false,
                "wrapper" => [
                    "width" => "",
                    "class" => "",
                    "id" => "",
                ],
                "min" => 1,
                "max" => 10,
                "layout" => "block",
                "rows_per_page" => 20,
                "button_label" => "Add Row",
                "collapsed" => "",
                "sub_fields" => [
                    [
                        "key" => "field_667c75165c62e",
                        "label" => "Also Include Bullet",
                        "name" => "include_bullets",
                        "aria-label" => "",
                        "type" => "text",
                        "instructions" => "",
                        "required" => false,
                        "conditional_logic" => false,
                        "wrapper" => [
                            "width" => "",
                            "class" => "",
                            "id" => "",
                        ],
                        "default_value" => "",
                        "maxlength" => "",
                        "placeholder" => "",
                        "prepend" => "",
                        "append" => "",
                        "parent_repeater" => "field_667c75085c62d",
                    ],
                ],
            ],
        ],
        "location" => [
            [
                [
                    "param" => "post_type",
                    "operator" => "==",
                    "value" => "product",
                ],
            ],
        ],
        "menu_order" => 0,
        "position" => "normal",
        "style" => "default",
        "label_placement" => "top",
        "instruction_placement" => "label",
        "hide_on_screen" => [],
        "active" => true,
        "description" => "",
        "show_in_rest" => false,
    ]);

	acf_add_local_field_group([
		'key' => 'group_6696cf9c9c536',
		'title' => 'QR Code Options',
		'fields' => array(
            array(
                'key' => 'field_673b9eff997c6',
                'label' => 'Qr code sample text',
                'name' => 'qr_code_sample_text',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
			array(
				'key' => 'field_6696cf9c10aa9',
				'label' => 'QR code scanning link',
				'name' => 'qr_code_scanning_link',
				'aria-label' => '',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
			array(
				'key' => 'field_6696d04c10aaa',
				'label' => 'QR code center logo',
				'name' => 'qr_code_center_logo',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
			array(
				'key' => 'field_6696d0a510aab',
				'label' => 'QR code heading text',
				'name' => 'qr_code_heading_text',
				'aria-label' => '',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'maxlength' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_66983ea8e8ea3',
				'label' => 'Dummy QR code for form display',
				'name' => 'dummy_qr_code',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'qr-code-options',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	]);

    acf_add_local_field_group(array(
        'key' => 'group_669fd16c986af',
        'title' => 'Default Shipping Cost',
        'fields' => array(
            array(
                'key' => 'field_669fd16d177dc',
                'label' => 'Default Cost',
                'name' => 'default_cost',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'default-shipping-cost',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_66915bec5498d',
        'title' => 'Shipping Types',
        'fields' => array(
            array(
                'key' => 'field_66915bedcb725',
                'label' => 'Select Pickup Location',
                'name' => 'select_store_location',
                'aria-label' => '',
                'type' => 'relationship',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array('store'),
                'post_status' => '',
                'taxonomy' => '',
                'filters' => array('search', 'post_type', 'taxonomy'),
                'return_format' => 'object',
                'min' => '',
                'max' => '',
                'elements' => '',
                'bidirectional' => 0,
                'bidirectional_target' => array(),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'shipping_type',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_66958bfebb96d',
        'title' => 'store cost',
        'fields' => array(
            array(
                'key' => 'field_66958bff536ce',
                'label' => 'shipping cost',
                'name' => 'shipping_cost',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66958c46536d0',
                'label' => 'store address',
                'name' => 'store_address',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_66958c62536d1',
                'label' => 'store phone',
                'name' => 'store_phone',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'store',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
});